theme: minima
default_lang: en
languages: ["en", "fr", "pt", "it", "lu"]
excerpt_separator: '<!-- more -->'

permalink: /:lang/:title.html
title: memorecord
exclude: [scripts, d3]
google_analytics: UA-115120497-1
